version: '3.8'
 
networks:
 default:
   external: false
   name: medical-scheduler
 
services:
 skeleton-app-postgres:
   image: "postgres:13-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: medical-scheduler-postgres
   environment:
     - POSTGRES_PASSWORD=12345678
     - POSTGRES_USER=postgres
     - POSTGRES_DB=medical-scheduler
   volumes:
     - ./db_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"